### ISSUE TITLE
podspec validation error

### ISSUE THREAD

**Issue by ashfaque2017** [CocoaPods/Molinillo#92]
Getting the following error for `pod spec lint` using cocoapods (1.3.0) and molinillo (0.6.4)

```- ERROR | [iOS] unknown: Encountered an unknown error (undefined method `version' for #<Molinillo::Resolver::Resolution::PossibilitySet:0x007f8b003223b8>) during validation.```

Below is the podspec file

```
Pod::Spec.new do |s|

  s.name         = "ThreeRingControl"
  s.version      = "1.0.0"
  s.summary      = "A three-ring control like the Activity status bars"
  s.homepage     = "http://raywenderlich.com"
  s.license      = {:type => "MIT" }
  s.authors       = { "Ashfaque Mohammad" => "ashfaque.os.2015@gmail.com" }
  s.source       = { :git => "https://github.com/ashfaque2017/ThreeRingControl.git", :tag => "1.0.0" }
  s.source_files  = "./ThreeRingControl/*.{h,swift}"
  s.resources    = "ThreeRingControl/*.mp3"
  s.platform     = :ios, "11.2"
end
```

Not sure what is wrong with this podspec file?

**Comment by dnkoutso** [comment]
Molinillo 0.6.x only works with CocoaPods 1.4.0. How did you end up with this combination?

**Comment by ashfaque2017** [comment]
I am new to CocoaPods and setting it up for the first time. Here are the step I went through:

1. Installed CocoaPods `gem install cocoapods --user-install`
2. When I ran a CocoaPods command it complained that the following Gemfile is missing `/User-home/.gem/ruby/2.0.0/gems/cocoapods-1.3.0/Gemfile`
3. Googled around, and manually created the above Gemfile with the following contents
```
source 'https://rubygems.org'

gem 'cocoapods', :git => 'https://github.com/CocoaPods/CocoaPods.git'
gem 'cocoapods-core', :git => 'https://github.com/CocoaPods/Core.git'
gem 'xcodeproj', :git => 'https://github.com/CocoaPods/Xcodeproj.git'

gem 'cocoapods-keys', :git => 'https://github.com/orta/cocoapods-keys.git'

gem 'xcpretty'
gem 'sbconstants'
```
4. Ran `bundle install` for the above Gemfile, which did the following
```
Fetching https://github.com/CocoaPods/CocoaPods.git
Fetching https://github.com/CocoaPods/Core.git
Fetching https://github.com/CocoaPods/Xcodeproj.git
Fetching https://github.com/orta/cocoapods-keys.git
Warning: Your Ruby version is compiled against a copy of OpenSSL that is very old. Starting in January 2018, RubyGems.org will refuse connection requests from these very old
versions of OpenSSL. If you will need to continue installing gems after January 2018, please follow this guide to upgrade: http://ruby.to/tls-outdated.
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
RubyGems 2.0.14.1 is not threadsafe, so your gems will be installed one at a time. Upgrade to RubyGems 2.1.0 or higher to enable parallel gem installation.
Using CFPropertyList 2.3.6
Using ZenTest 4.11.1
Using RubyInline 3.12.4
Using concurrent-ruby 1.0.5
Using i18n 0.9.1
Using minitest 5.10.3
Using thread_safe 0.3.6
Using tzinfo 1.2.4
Using activesupport 4.2.10
Using bundler 1.16.1
Using claide 1.0.2
Using fuzzy_match 2.0.4
Using nap 1.1.0
Using cocoapods-core 1.4.0.rc.1 from https://github.com/CocoaPods/Core.git (at master@33299ad)
Using cocoapods-deintegrate 1.0.1
Using cocoapods-downloader 1.1.3
Using cocoapods-plugins 1.0.0
Using cocoapods-search 1.0.0
Using cocoapods-stats 1.0.0
Using netrc 0.11.0
Using cocoapods-trunk 1.3.0
Using cocoapods-try 1.1.0
Using colored2 3.1.2
Using escape 0.0.4
Using fourflusher 2.0.1
Using gh_inspector 1.0.3
Using molinillo 0.6.4
Using ruby-macho 1.1.0
Using nanaimo 0.2.3
Using xcodeproj 1.5.4 from https://github.com/CocoaPods/Xcodeproj.git (at master@976144e)
Using cocoapods 1.4.0.rc.1 from https://github.com/CocoaPods/CocoaPods.git (at master@88276c4)
Using dotenv 2.2.1
Using osx_keychain 1.0.1
Using cocoapods-keys 2.0.0 from https://github.com/orta/cocoapods-keys.git (at master@83b0c3f)
Using rouge 2.0.7
Using sbconstants 1.2.0
Using xcpretty 0.2.8
Bundle complete! 6 Gemfile dependencies, 37 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

**Comment by dnkoutso** [comment]
Based on the output you are not using `bundle exec pod lib lint ...` so it doesnt use the bundle "sandbox" to execute commands.

You can simplify your `Gemfile` too:
```ruby
source 'https://rubygems.org'

gem 'cocoapods', '~> 1.3'
```
or
```ruby
source 'https://rubygems.org'

gem 'cocoapods', 1.4.0.rc.1'
```

Closing as this appears to be a user error.

**Comment by ashfaque2017** [comment]
Thank you, will try that.
